### ISSUE TITLE
Схема базы данных

### ISSUE THREAD

**Issue by pr0head** [MaxOnNet/PokeStats#1]
Здравствуйте.
Подскажите, пожалуйста, где можно взять схему таблиц базы данных.
При попытке запуска Worker или Application ругается на отсутствие нужных для работы таблиц.

**Comment by MaxOnNet** [comment]
Доброго времени суток. Проект находится на стадии глубокой альфы. С изменением в API его постоянно банят :( Пока ничего с этим поделать не могу. Дамп текущей БД, в течении часа закоммичу.
